using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SaveState.Generator
{
    /// <summary>
    /// Emits the assembly-local registration helper for every <c>[SaveService]</c> type:
    ///
    /// <code>
    /// internal static class SaveState.Generated.SaveServiceRegistration
    /// {
    ///     internal static SaveRegistry AddGeneratedServices(this SaveRegistry registry, Func&lt;Type, object&gt; resolve);
    /// }
    /// </summary>
    ///
    /// <para><b>Why a separate generator</b> (rather than another branch of the file/section generator): it has no
    /// relationship to the save-file graph at all — it only needs the list of services. Keeping it separate means it
    /// keeps working (and keeps its diagnostics independent) even while a save-file model is temporarily invalid,
    /// and it keeps both generators' incremental pipelines simple.</para>
    ///
    /// <para><b>Why not reflection</b>: a container integration should never have to scan assemblies or guess how a
    /// service is constructed. The host passes a resolve delegate (for example
    /// <c>type =&gt; provider.GetRequiredService(type)</c>) and this helper names each service explicitly — so a
    /// forgotten registration is impossible and the compiler checks every cast.</para>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class SaveServiceRegistrationGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<RegistrationModel?> services = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    WellKnownNames.SaveServiceAttribute,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => RegistrationModel.Create(ctx))
                .Where(static model => model is not null);

            IncrementalValueProvider<EquatableArray<RegistrationModel>> collected = services
                .Collect()
                .Select(static (models, _) => new EquatableArray<RegistrationModel>(
                    models.Where(static m => m is not null).Select(static m => m!).OrderBy(static m => m.ClassFullName, System.StringComparer.Ordinal)));

            context.RegisterSourceOutput(collected, static (spc, models) => Emit(spc, models));
        }

        private static void Emit(SourceProductionContext context, EquatableArray<RegistrationModel> models)
        {
            List<RegistrationModel> services = models
                .Where(static m => m.Usable)
                .GroupBy(static m => m.ClassFullName, System.StringComparer.Ordinal)
                .Select(static g => g.First())
                .OrderBy(static m => m.ClassFullName, System.StringComparer.Ordinal)
                .ToList();

            if (services.Count == 0)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("// Generated by SaveState.Generator: registration helper for every [SaveService] type.");
            sb.AppendLine();
            sb.AppendLine("namespace SaveState");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Generated registration helper: adds every [SaveService] type of this assembly to a registry.</summary>");
            sb.AppendLine("    internal static class SaveServiceRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Adds all services marked with [SaveService] to <paramref name=\"registry\"/>,");
            sb.AppendLine("        /// resolving each instance through <paramref name=\"resolve\"/>");
            sb.AppendLine("        /// (a DI container: <c>type =&gt; provider.GetRequiredService(type)</c>);");
            sb.AppendLine("        /// a plain factory lookup works just as well.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        internal static global::SaveState.SaveRegistry AddGeneratedServices(");
            sb.AppendLine("            this global::SaveState.SaveRegistry registry,");
            sb.AppendLine("            global::System.Func<global::System.Type, object> resolve)");
            sb.AppendLine("        {");

            foreach (RegistrationModel service in services)
            {
                sb.Append("            registry.Add((")
                    .Append(service.ClassFullName)
                    .Append(")resolve(typeof(")
                    .Append(service.ClassFullName)
                    .AppendLine(")));");
            }

            sb.AppendLine();
            sb.AppendLine("            return registry;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("SaveServiceRegistration.Generated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        /// <summary>One <c>[SaveService]</c> type, reduced to what the registration helper needs.</summary>
        private sealed class RegistrationModel : System.IEquatable<RegistrationModel>
        {
            private RegistrationModel(string classFullName, bool usable)
            {
                ClassFullName = classFullName;
                Usable = usable;
            }

            public string ClassFullName { get; }

            /// <summary>
            /// False for a nested/generic service. Diagnostics for those are reported by the file/section
            /// generator (<c>SAV005</c>) - this generator stays silent on purpose, so one problem is never
            /// reported twice by two different owners.
            /// </summary>
            public bool Usable { get; }

            public static RegistrationModel? Create(GeneratorAttributeSyntaxContext context)
            {
                if (context.TargetSymbol is not INamedTypeSymbol type)
                {
                    return null;
                }

                bool usable = type.ContainingType == null && !type.IsGenericType;
                return new RegistrationModel(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), usable);
            }

            public bool Equals(RegistrationModel? other)
            {
                return other != null
                       && Usable == other.Usable
                       && string.Equals(ClassFullName, other.ClassFullName, System.StringComparison.Ordinal);
            }

            public override bool Equals(object? obj)
            {
                return Equals(obj as RegistrationModel);
            }

            public override int GetHashCode()
            {
                unchecked
                {
                    return (ClassFullName.GetHashCode() * 31) + (Usable ? 1 : 0);
                }
            }
        }
    }
}
